### ISSUE TITLE
Error: Cannot find module '../build/Release/magic'

### ISSUE THREAD

**Issue by csmicfool** [bregenspan/tess-search#2]
Hello,

I'm trying to use this tool and keep running in to an error message:

> G:\...\tess-search-master>node cli.js '150501[DC]'
> module.js:549
>     throw err;
>     ^
> 
> Error: Cannot find module '../build/Release/magic'
>     at Function.Module._resolveFilename (module.js:547:15)
>     at Function.Module._load (module.js:474:25)
>     at Module.require (module.js:596:17)
>     at require (internal/module.js:11:18)
>     at Object.<anonymous> (G:\Users\Jacob\Downloads\tess-search-master\tess-sear
> ch-master\node_modules\mmmagic\lib\index.js:3:13)
>     at Module._compile (module.js:652:30)
>     at Object.Module._extensions..js (module.js:663:10)
>     at Module.load (module.js:565:32)
>     at tryModuleLoad (module.js:505:12)
>     at Function.Module._load (module.js:497:3)
> 

Any guidance is appreciated.

**Comment by csmicfool** [comment]
this appeared to be environmental.  Was able to get past this on another machine.
